### PR TITLE
TypeScript definition file

### PR DESCRIPTION
**Pull request by sbusch**
I noticed many missing parts in the TypeScript definitions for the React `<FilePond />` component (implemented in `react-filepond`, types from `@types/react-filepond` from DefinitelyTyped project) 

I first tried to add them to DefinitelyTyped in a PR, but then I noticed that the definitions there were the (now outdated) base of the up-to-date definitions that are bundled with `filepond`.  After careful removing duplicate definitions I managed to get a minimal type definition. After that I decided to move the work to `react-filepond` to provide bundled type definitions.

P.S: you can see the first commits when I worked on DefinitelyTyped at <https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...sbusch:sbusch--react-filepond--2020-08b> (cherry-picked to new branch)

I also added a `dtslint` setup similar to the setup at `filepond`.

After this PR gets merged (if you merge it, I hope so 😄 ), I will create a PR at DefinitelyTyped deprecating the type def for `react-filepond` there.

### CODE REVIEW

**Comment by rikschennink** [comment]
Quick check, isn't this the same as? https://github.com/pqina/react-filepond/pull/150

**Comment by sbusch** [comment]
Wow, you're right. I was not aware of #150 🥴 

Although there are may similarities, I think my PR has some advantages over #150:

- definitions for instance methods (`setOptions`, `addFile`, ..) are imported from `filepond` instead of duplicating them
- which instance methods exist is also dynamically taken from `filepond`, aligned with the code of `react-filepond` which takes all keys except some from a defined list. So new methods at type definition for the `filepond` instance will automatically appear here.
- there is no <FilePondFile/> component, I removed that
- I removed some exports which aren't really exported by `react-filepond` (according to its implementation)

I can offer to (carefully, of course) check @WillemDuPlessis changes at #150 and add any improvements to my PR, if you agree.

(I'm AFK for some hours now...)

**Comment by sbusch** [comment]
I compared the changes from PR #150 with mine, and just pushed three commits with minor changes (add lockfile 2c59916, ignore and remove /dist folder f06fe9f and give credits b8f73ee)

In addition to the differences listed in my previous comment, there are more differences:

- I opted for keeping auto-exports turned off (via `export {}`) since I have some helper types (`Omit` and `FilteredMethods`) which I don't want to inline (explicit names = better readability).
- as I wrote previously, I removed the non-existent `<FilePondFile/>` React component (please correct me if I'm wrong), and I also removed `FilePondOrigin` and `FileProps` which were used only in that context
- I only export types unique for `react-filepond`, and - as I wrote earlier - there are some types which are re-exported from `filepond` (e.g. `FileStatus`, `FilePondInitialFile`, ...) In my opinion 

I compared the changes from PR #150 with mine, and just pushed three commits with minor changes (add lockfile 2c59916, ignore and remove /dist folder f06fe9f and give credits b8f73ee)

In addition to the differences listed in my previous comment, there are more differences:

- I opted for keeping auto-exports turned off (via `export {}`) since I have some internal helper types (`Omit` and `FilteredMethods`) which I wanted to keep (inlining reduces readability, IMO)
- as I wrote previously, I removed the non-existent `<FilePondFile/>` React component (please correct me if I'm wrong), and I also removed `FilePondOrigin` and `FileProps` which were used only in conjunction with that component
- I only export types unique for `react-filepond` plus `registerPlugin` and `FileStatus` (which [the `react-filepond` implementation re-exports from `filepond`](https://github.com/pqina/react-filepond/blob/master/lib/index.js#L7)), but - as I wrote earlier - there are more types which are re-exported from `filepond` (e.g. `ActualFileObject`, `FilePondInitialFile`, ...) that I removed. Those who need those types explicitly can import them directly from `filepond`. Each package exports just the types it owns and the distribution of responsitiblities is clear.
- I kept the package version at `7.0.1`. It's no breaking change, but you should decide if `7.0.2` or `7.1.0` is better (I have no opinion about this)

**Comment by sbusch** [comment]
And @WillemDuPlessis:

I'm sorry for the duplicate PR!

I **really** wasn't aware of your effort, and was shocked when @rikschennink pointed me to it. I hope you believe me. It seems we started at the same time. If I had noticed your PR, I had contributed there for sure (would have saved me some hours, also)

**Comment by WillemDuPlessis** [comment]
> And @WillemDuPlessis:
> 
> I'm sorry for the duplicate PR!
> 
> I **really** wasn't aware of your effort, and was shocked when @rikschennink pointed me to it. I hope you believe me. It seems we started at the same time. If I had noticed your PR, I had contributed there for sure (would have saved me some hours, also)

No Problem @sbusch! I just noticed that the type definition was out of date while using it in a project and wanted to updated it to make the newer functionality available.
Looking at your efforts I'm glad to support your PR over mine as you seem to have put much more effort in and it seems to be more complete.
@rikschennink Do you think we should rather continue on with this PR rather than #150?

**Comment by rikschennink** [comment]
@WillemDuPlessis I'm not super familiar with TypeScript (still learning) so it's difficult for me to asses which branch is more complete. I leave this choice up to you, if you feel this branch is better/further along then I'm fully okay with continuing on #151 and closing #150

**Comment by WillemDuPlessis** [comment]
@sbusch Would you consider including the gitignore changes and package-lock file as per #150? That way we can include all the changes requested without having to complete both PR's.
I'll be happy to close out #150 in support of your PR as I myself am no guru at TypeScript and your knowledge of the version requirements and package composition best practice makes this the clear winner between the 2.

**Comment by sbusch** [comment]
@WillemDuPlessis they're already there, see

* add lockfile 2c59916
* ignore and remove /dist folder f06fe9f
* give credits b8f73ee

**Comment by WillemDuPlessis** [comment]
> @WillemDuPlessis they're already there, see
> 
> * add lockfile [2c59916](https://github.com/pqina/react-filepond/commit/2c59916020c805bef7528e979afbeeab261f3f07)
> * ignore and remove /dist folder [f06fe9f](https://github.com/pqina/react-filepond/commit/f06fe9fbfd18105f3c8f2c73509a00b604d197bf)
> * give credits [b8f73ee](https://github.com/pqina/react-filepond/commit/b8f73eea85ec0f89584f3d33ebcdd61d8e795d6f)

Then I am happy to put y support behind this PR, @rikschennink.  I will close #150 and we can continue the process of integrating @sbusch's changes.

**Comment by sbusch** [comment]
👍

@WillemDuPlessis as I'm also no guru I would greatly appreciate if you could test this `index.d.ts` in your project! 

(it's working in my project, and passed the test as long as I worked on it as a DefinitelyTyped PR)

**Comment by guicara** [comment]
Hello,

> I would greatly appreciate if you could test this index.d.ts in your project!

I would like to replace the outdated `@types/react-filepond` with your new definition file.

But I am not sure how to proceed. I have remove `@types/react-filepond` from my dependencies (packages.json) and created a custom definition file (ReactFilepond.d.ts). My project TypeScript configuration file is already configured to load custom definitions.

```
// tsconfig.json
{
  "compilerOptions": {
   ...
    "typeRoots": [
      "src/types",
      "node_modules/@types"
    ]
  },
}
```

```
// src/types/ReactFilepond.d.ts

// it is a copy and paste of your index.d.ts file
```

TypeScript do not find the custom definition:
```
TS7016: Could not find a declaration file for module 'react-filepond'. '/node_modules/react-filepond/dist/react-filepond.js' implicitly has an 'any' type. 
Try `npm install @types/react-filepond` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-filepond';` 
```

Btw, I'm a newbie with TypeScript definition. And please do not hesitate to tell me if it's the wrong place to ask this question.

Thanks,

**Comment by guicara** [comment]
Hello,

> I would greatly appreciate if you could test this index.d.ts in your project!

I have successfully tested your definition file on my project (replacing the outdated `@types/react-filepond` that I have removed from my dependencies).

However, I had to change the definition for `acceptedFileTypes`.

```
export interface FilePondProps extends FilePondOptions {
  acceptedFileTypes?: React.InputHTMLAttributes<any>['accept'];
}
```

acceptedFileTypes should be an array of string according to the plugin definition file: https://github.com/pqina/filepond-plugin-file-validate-type/blob/master/types/index.d.ts

```
export interface FilePondProps extends FilePondPluginFileValidateTypeProps, FilePondOptions {}
```

I also had to rename `Upstream_FilePond` with `UpstreamFilePond`:

```
ESLint: Identifier 'Upstream_FilePond' is not in camel case.(@typescript-eslint/camelcase)
```

**Comment by sbusch** [comment]
@guicara thanks for testing the PR!

How did you test the new type definitions, did you modify the files in your local `node_modules/react-filepond/...`?

----

Regarding `acceptedFileTypes`:

Good catch 👍 Unfortunately, we're both right: 

- `react-filepond` renders `acceptedFileTypes` as `accept` prop of an `<input>` element ([source](https://github.com/pqina/react-filepond/blob/7deaee287dd24614706f2401dcf39df6207ef5ef/lib/index.js#L95-L120)). That's why I declared it as `React.InputHTMLAttributes<any>['accept']`. "The accept attribute value is a string that defines the file types the file input should accept. This string is a comma-separated list of unique file type specifiers" (from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept))
- `filepond-plugin-file-validate-type` uses the same option, but requires an array

Proposed solution: make *both* implementations accept `string` or `string[]`, converting to `string[]` or `string` respectively, as needed. But this is only possible if the values are evaluated the same way in both places. @rikschennink can you confirm this? Do you think this approach make sense?

*Note: `filepond` itself doesn't use `acceptedFileTypes` at all. But there's the option `allowSyncAcceptAttribute`, and the docs for this mention `acceptedFileTypes`. But because `allowSyncAcceptAttribute` is not used anywhere, I just submitted PR https://github.com/pqina/filepond/pull/562 removing this option.*

----

Regarding `Upstream_FilePond`:

Because there's no ESLint setup in `react-filepond`, I assume that the linter warning is coming from a global ESLint configuration of your editor or system, right? Anyway, I now also renamed it to `UpstreamFilePond`, see 6f374d0.

**Comment by guicara** [comment]
Hello @sbusch,

Thanks for your reply.

> @guicara thanks for testing the PR!
> 
> How did you test the new type definitions, did you modify the files in your local `node_modules/react-filepond/...`?
> 

I have first removed `@types/react-filepond` from my `packages.json`. Then, I have created _(to be exact, updated because [I already had a custom definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43601#issuecomment-680897605) for React Filepond, required on my project to override some outdated definitions)_ a custom definition file.

tsconfig.json
```
{
  "compilerOptions": {
    ...
    "typeRoots": [
      "src/types",
      "node_modules/@types"
    ]
  },
}

```

src/types/ReactFilepond.d.ts:
```
// Based on definitions by Zach Posten for React-Filepond <https://github.com/zposten>
// Updated by FilePond Contributors
// WIP https://github.com/pqina/react-filepond/pull/151
// See the docs for more info on any given prop
// https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#setting-options

declare module 'react-filepond' {
    // and this is just a copy-paste of your index.d.ts file
    // https://github.com/pqina/react-filepond/blob/6f374d0c8451ecc2cf743e547f62b9ca56c16365/types/index.d.ts
}
```

That way I was able to test your PR. Of course, I will _"remove"_ this custom definition file when your PR will me merged and that a new version of React Filepond will de released.

_NB: to be totally exact, I will always need a custom definition file to override the `FilePondProps` interface because of the optional FilePond plugins and their props. Something like that:_
```
import { FilePondProps } from 'react-filepond';
import { FilePondPluginImagePreviewProps } from 'filepond-plugin-image-preview';
import { FilepondPluginImageExifOrientationProps } from 'filepond-plugin-image-exif-orientation';
import { FilePondPluginFileValidateSizeProps } from 'filepond-plugin-file-validate-size';
import { FilePondPluginFileValidateTypeProps } from 'filepond-plugin-file-validate-type';

declare module 'react-filepond' {
    interface FilePondProps
        extends FilePondPluginImagePreviewProps,
            FilePondPluginFileValidateSizeProps,
            FilePondPluginFileValidateTypeProps,
            FilepondPluginImageExifOrientationProps,
            FilePondOptions {}
}
```

> Regarding `acceptedFileTypes`:
> (...)
> Proposed solution: make _both_ implementations accept `string` or `string[]`, converting to `string[]` or `string` respectively, as needed. But this is only possible if the values are evaluated the same way in both places. @rikschennink can you confirm this? Do you think this approach make sense?

It would be great if we can make _both_ implementations accept `string` and `string[]`.

> Regarding `Upstream_FilePond`:
> 
> Because there's no ESLint setup in `react-filepond`, I assume that the linter warning is coming from a global ESLint configuration of your editor or system, right? Anyway, I now also renamed it to `UpstreamFilePond`, see [6f374d0](https://github.com/pqina/react-filepond/commit/6f374d0c8451ecc2cf743e547f62b9ca56c16365).

Indeed! I hadn't thought of that when I posted my message yesterday!
Thanks for the commit anyway.

**Comment by sbusch** [comment]
@guicara thanks for your response!

I changed the definition of `acceptedFileTypes` back to the old one (`string[]`, as it was used at DefinitelyTyped). This is in accordance to the type def of `filepond-plugin-file-validate-type` and is also technically working because assigning an array to a string prop results in React rendering a comma-separated list, so this will work for `react-filepond`also. I wasn't aware of this behavior. In a 100% TypeScript setup the type checker would complain (verified it with different Codepens), but since `react-filepond` is no native TypeScript project it doesn't matter but just works:tm:

So there's IMO no issue left which blocks merging of this PR. Does everyone agree?

----

@guicara this my approach for typesafe use of FilePond with plugins, maybe this spares you from overriding the bundled types:

```typescript
import { FilePond, FilePondProps, registerPlugin } from 'react-filepond';
import FilePondPluginFileMetadata, {  FilepondPluginFilepondPluginFileMetadataProps /* sic! */ } from 'filepond-plugin-file-metadata';
import FilePondPluginImageExifOrientation, { FilepondPluginImageExifOrientationProps } from 'filepond-plugin-image-exif-orientation';
import FilePondPluginImagePreview, { FilePondPluginImagePreviewProps } from 'filepond-plugin-image-preview';
import FilePondPluginFileValidateSize, { FilePondPluginFileValidateSizeProps } from 'filepond-plugin-file-validate-size';
import FilePondPluginImageEdit, { FilePondPluginImageEditProps } from 'filepond-plugin-image-edit';

// ...

// setup FilePond, register plugins */
registerPlugin(
  FilePondPluginFileMetadata,
  FilePondPluginImageExifOrientation,
  FilePondPluginImagePreview,
  FilePondPluginFileValidateSize,
  FilePondPluginImageEdit
);

// ...

// Create a type-safe FilePond component with plugins, just for TypeScript
const FilePondWithPlugins = FilePond as React.ComponentClass<
  | FilePondProps
  | FilepondPluginFilepondPluginFileMetadataProps // sic!
  | FilepondPluginImageExifOrientationProps
  | FilePondPluginImagePreviewProps
  | FilePondPluginFileValidateSizeProps
  | FilePondPluginImageEditProps
>;

// ...

// Usage in JSX:
<FilePondWithPlugins .…. />
```

**Comment by rikschennink** [comment]
@sbusch Just let me know when I'm needed 👍

**Comment by sbusch** [comment]
@rikschennink it's ready to be merged :-)

**Comment by sbusch** [comment]
Short follow-up @rikschennink : in the release notes you should additionally instruct users to uninstall @types/react-filepond

**Comment by rikschennink** [comment]
@sbusch 👍

Couple questions:

- I guess we have a `filepond` `peerDependency` and `devDependency` because the FilePond types are now required for devving?

- Can we "just" remove "dist/" without problems? Not sure if some developers download the repo and simply use the dist files instead of npm, so am a bit hesitant to remove it.

**Comment by sbusch** [comment]
@rikschennink 

- `devDependency`: yes, it's a bit redundant, but when you're developing in TypeScript it's a mandatory dependency from my point of view. Shouldn't hurt for non-TypeScript developers IMO, but please correct me if I'm wrong (as I am no library maintainer, I'm maybe unaware of possible pitfalls)
- removal of `/dist`: that was just one of the changes of https://github.com/pqina/react-filepond/pull/150 I took over. I suppose `/dist` is not needed in the repo since the huge majority of React devs should use `npm`, but I don't know. Can revert this change if you want.

If you want me to change something here just let me know...

**Comment by rikschennink** [comment]
@sbusch Thanks for clarifying, let's leave 'dist/' in just to be safe :)

**Comment by sbusch** [comment]
@rikschennink Ok, `/dist` is back again :-)

**Comment by rikschennink** [comment]
@sbusch Merged and published, let me know if there's any issues 👍

**Comment by sbusch** [comment]
I updated my project, removing all local patches. It still compiles.

And I just submitted PR <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47374> to DefinitelyTyped to deprecate [@types/react-filepond](https://npm.im/@types/react-filepond).

Thank you all!

**Comment by rikschennink** [comment]
@sbusch Fantastic, glad to hear that.

Thanks so much for contributing everyone, it's appreciated ❤️

**Pull request merged**
